### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by njgibbon** [njgibbon/sek#6]
* No superclass needed for 'context' types.
* No subclass needed for 'runner' type.
* DI for context into runner and into checks.
* Dynamic imports for checks into runner.

**Comment by nickgibbon-nationwide** [comment]
* Superclass removal for Context - Done.
* EKSRunner still used. Spiked dynamic imports of checks based on path but no bueno. Made several streamlining and added some dynamic elements though - Done / Won't Do.
* DI into checks. Still open whether to inject context into the runner or not.

**Comment by nickgibbon-nationwide** [comment]
Enough to close this and if context turns into injection then will be included as a refactor.

**Comment by njgibbon** [comment]
* Superclass removal for Context - Done.
* EKSRunner still used. Spiked dynamic imports of checks based on path but no bueno. Made several streamlining and added some dynamic elements though - Done / Won't Do.
* DI into checks. Still open whether to inject context into the runner or not.

Enough to close this and if context turns into injection then will be included as a refactor.
